-- GENERATED from db/schema.sql by `python -m ingest.load_hana --gen-sqlite`. Do not edit.

CREATE TABLE FF_CFG_PARAM (
    NAME TEXT NOT NULL,
    DATE_VALUE TEXT,
    TEXT_VALUE TEXT,
    PRIMARY KEY (NAME)
);

CREATE TABLE FF_REF_FORMULATION (
    FORM_ID TEXT NOT NULL,
    GENERIC TEXT NOT NULL,
    DOSAGE_FORM TEXT,
    STRENGTH TEXT,
    UNIT TEXT,
    NLEM_LEVEL TEXT,
    THERAPEUTIC_CLASS TEXT,
    SOURCE TEXT NOT NULL,
    SOURCE_URL TEXT,
    FETCHED_AT TEXT,
    IS_PROXY TEXT NOT NULL,
    PRIMARY KEY (FORM_ID)
);

CREATE TABLE FF_REF_CEILING_PRICE (
    FORM_ID TEXT NOT NULL,
    EFFECTIVE_FROM TEXT NOT NULL,
    SO_NUMBER TEXT NOT NULL,
    CEILING_PRICE NUMERIC NOT NULL,
    PARA TEXT,
    GST_RATE NUMERIC,
    SOURCE TEXT NOT NULL,
    SOURCE_URL TEXT,
    FETCHED_AT TEXT,
    IS_PROXY TEXT NOT NULL,
    PRIMARY KEY (FORM_ID, EFFECTIVE_FROM, SO_NUMBER)
);

CREATE TABLE FF_REF_API (
    API_ID TEXT NOT NULL,
    NAME TEXT NOT NULL,
    HS8 TEXT,
    KSM_ID TEXT,
    SOURCE TEXT NOT NULL,
    SOURCE_URL TEXT,
    FETCHED_AT TEXT,
    IS_PROXY TEXT NOT NULL,
    PRIMARY KEY (API_ID)
);

CREATE TABLE FF_REF_FORM_API (
    FORM_ID TEXT NOT NULL,
    API_ID TEXT NOT NULL,
    API_MG_PER_UNIT NUMERIC,
    SOURCE TEXT NOT NULL,
    SOURCE_URL TEXT,
    FETCHED_AT TEXT,
    IS_PROXY TEXT NOT NULL,
    PRIMARY KEY (FORM_ID, API_ID)
);

CREATE TABLE FF_REF_BOM_ASSUMPTION (
    FORM_ID TEXT NOT NULL,
    API_G_PER_UNIT NUMERIC,
    YIELD NUMERIC,
    CONVERSION_COST_INR NUMERIC,
    PACKAGING_COST_INR NUMERIC,
    FREIGHT_COST_INR NUMERIC,
    SOURCE TEXT NOT NULL,
    SOURCE_URL TEXT,
    FETCHED_AT TEXT,
    IS_PROXY TEXT NOT NULL,
    PRIMARY KEY (FORM_ID)
);

CREATE TABLE FF_REF_API_COST_MONTHLY (
    API_ID TEXT NOT NULL,
    MONTH TEXT NOT NULL,
    UNIT_VALUE_INR_KG NUMERIC,
    QTY_KG NUMERIC,
    SOURCE TEXT NOT NULL,
    SOURCE_URL TEXT,
    FETCHED_AT TEXT,
    IS_PROXY TEXT NOT NULL,
    PRIMARY KEY (API_ID, MONTH)
);

CREATE TABLE FF_REF_API_ORIGIN (
    API_ID TEXT NOT NULL,
    MONTH TEXT NOT NULL,
    COUNTRY TEXT NOT NULL,
    SHARE NUMERIC,
    SOURCE TEXT NOT NULL,
    SOURCE_URL TEXT,
    FETCHED_AT TEXT,
    IS_PROXY TEXT NOT NULL,
    PRIMARY KEY (API_ID, MONTH, COUNTRY)
);

CREATE TABLE FF_REF_MANUFACTURER (
    ID TEXT NOT NULL,
    NAME TEXT NOT NULL,
    STATE TEXT,
    LICENCE_NO TEXT,
    SOURCE TEXT NOT NULL,
    SOURCE_URL TEXT,
    FETCHED_AT TEXT,
    IS_PROXY TEXT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE FF_REF_PRODUCER (
    FORM_ID TEXT NOT NULL,
    MANUFACTURER_ID TEXT NOT NULL,
    EVIDENCE_SOURCE TEXT,
    MARKET_SHARE NUMERIC,
    SOURCE TEXT NOT NULL,
    SOURCE_URL TEXT,
    FETCHED_AT TEXT,
    IS_PROXY TEXT NOT NULL,
    PRIMARY KEY (FORM_ID, MANUFACTURER_ID)
);

CREATE TABLE FF_REF_WPI (
    MONTH TEXT NOT NULL,
    SERIES TEXT NOT NULL,
    INDEX_VALUE NUMERIC,
    SOURCE TEXT NOT NULL,
    SOURCE_URL TEXT,
    FETCHED_AT TEXT,
    IS_PROXY TEXT NOT NULL,
    PRIMARY KEY (MONTH, SERIES)
);

CREATE TABLE FF_REF_NSQ_ALERT (
    ALERT_ID TEXT NOT NULL,
    MONTH TEXT NOT NULL,
    DRUG TEXT NOT NULL,
    BATCH TEXT NOT NULL,
    MANUFACTURER_ID TEXT,
    FORM_ID TEXT,
    REASON TEXT,
    SOURCE TEXT NOT NULL,
    SOURCE_URL TEXT,
    FETCHED_AT TEXT,
    IS_PROXY TEXT NOT NULL,
    PRIMARY KEY (ALERT_ID)
);

CREATE TABLE FF_MM_MARA (
    MATNR TEXT NOT NULL,
    MAKTX TEXT,
    GENERIC TEXT,
    STRENGTH TEXT,
    MEINS TEXT,
    VED TEXT,
    ABC TEXT,
    FSN TEXT,
    RAUBE TEXT,
    XCHPF TEXT,
    FORM_ID TEXT,
    SOURCE TEXT NOT NULL,
    SOURCE_URL TEXT,
    FETCHED_AT TEXT,
    IS_PROXY TEXT NOT NULL,
    PRIMARY KEY (MATNR)
);

CREATE TABLE FF_MM_LFA1 (
    LIFNR TEXT NOT NULL,
    NAME1 TEXT NOT NULL,
    GSTIN TEXT,
    DRUG_LICENCE_NO TEXT,
    SPERR TEXT,
    SOURCE TEXT NOT NULL,
    SOURCE_URL TEXT,
    FETCHED_AT TEXT,
    IS_PROXY TEXT NOT NULL,
    PRIMARY KEY (LIFNR)
);

CREATE TABLE FF_MM_T001W (
    WERKS TEXT NOT NULL,
    NAME1 TEXT NOT NULL,
    ORT01 TEXT,
    REGIO TEXT,
    LOC_TYPE TEXT,
    SOURCE TEXT NOT NULL,
    SOURCE_URL TEXT,
    FETCHED_AT TEXT,
    IS_PROXY TEXT NOT NULL,
    PRIMARY KEY (WERKS)
);

CREATE TABLE FF_MM_MCHB (
    MATNR TEXT NOT NULL,
    WERKS TEXT NOT NULL,
    LGORT TEXT NOT NULL,
    CHARG TEXT NOT NULL,
    CLABS NUMERIC NOT NULL,
    CINSM NUMERIC,
    CSPEM NUMERIC,
    VFDAT TEXT NOT NULL,
    HSDAT TEXT,
    MANUFACTURER_ID TEXT,
    SOURCE TEXT NOT NULL,
    SOURCE_URL TEXT,
    FETCHED_AT TEXT,
    IS_PROXY TEXT NOT NULL,
    PRIMARY KEY (MATNR, WERKS, LGORT, CHARG)
);

CREATE TABLE FF_MM_MSEG (
    MBLNR TEXT NOT NULL,
    MJAHR INTEGER NOT NULL,
    ZEILE INTEGER NOT NULL,
    BWART TEXT NOT NULL,
    MATNR TEXT NOT NULL,
    WERKS TEXT NOT NULL,
    LGORT TEXT,
    CHARG TEXT,
    MENGE NUMERIC NOT NULL,
    MEINS TEXT,
    BUDAT TEXT NOT NULL,
    UMWRK TEXT,
    KOSTL TEXT,
    LIFNR TEXT,
    EBELN TEXT,
    EBELP INTEGER,
    SOURCE TEXT NOT NULL,
    SOURCE_URL TEXT,
    FETCHED_AT TEXT,
    IS_PROXY TEXT NOT NULL,
    PRIMARY KEY (MBLNR, MJAHR, ZEILE)
);

CREATE TABLE FF_MM_EKKO (
    EBELN TEXT NOT NULL,
    BSART TEXT,
    LIFNR TEXT NOT NULL,
    BEDAT TEXT NOT NULL,
    WAERS TEXT,
    SOURCE TEXT NOT NULL,
    SOURCE_URL TEXT,
    FETCHED_AT TEXT,
    IS_PROXY TEXT NOT NULL,
    PRIMARY KEY (EBELN)
);

CREATE TABLE FF_MM_EKPO (
    EBELN TEXT NOT NULL,
    EBELP INTEGER NOT NULL,
    MATNR TEXT NOT NULL,
    WERKS TEXT NOT NULL,
    MENGE NUMERIC NOT NULL,
    MEINS TEXT,
    NETPR NUMERIC,
    PEINH INTEGER,
    EINDT TEXT NOT NULL,
    SOURCE TEXT NOT NULL,
    SOURCE_URL TEXT,
    FETCHED_AT TEXT,
    IS_PROXY TEXT NOT NULL,
    PRIMARY KEY (EBELN, EBELP)
);

CREATE TABLE FF_MM_EBAN (
    BANFN TEXT NOT NULL,
    BNFPO INTEGER NOT NULL,
    MATNR TEXT NOT NULL,
    WERKS TEXT NOT NULL,
    MENGE NUMERIC NOT NULL,
    MEINS TEXT,
    PREIS NUMERIC,
    PEINH INTEGER,
    BADAT TEXT NOT NULL,
    LFDAT TEXT,
    FLIEF TEXT,
    AFNAM TEXT,
    STATUS TEXT,
    RUN_ID TEXT,
    SCENARIO_ID TEXT,
    SOURCE TEXT NOT NULL,
    SOURCE_URL TEXT,
    FETCHED_AT TEXT,
    IS_PROXY TEXT NOT NULL,
    PRIMARY KEY (BANFN, BNFPO)
);

CREATE TABLE FF_MM_COLDCHAIN (
    LOCATION TEXT NOT NULL,
    TS TEXT NOT NULL,
    TEMP_C NUMERIC,
    EXCURSION_FLAG INTEGER,
    SOURCE TEXT NOT NULL,
    SOURCE_URL TEXT,
    FETCHED_AT TEXT,
    IS_PROXY TEXT NOT NULL,
    PRIMARY KEY (LOCATION, TS)
);

CREATE TABLE FF_G_V (
    ID TEXT NOT NULL,
    TYPE TEXT NOT NULL,
    LABEL TEXT,
    PRIMARY KEY (ID)
);

CREATE TABLE FF_G_E (
    ID TEXT NOT NULL,
    SRC TEXT NOT NULL,
    DST TEXT NOT NULL,
    REL TEXT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE FF_AG_RUN (
    RUN_ID TEXT NOT NULL,
    STARTED_AT TEXT NOT NULL,
    FINISHED_AT TEXT,
    TRIGGER_TYPE TEXT NOT NULL,
    STATUS TEXT NOT NULL,
    FORMULATION_IDS_JSON TEXT,
    AS_OF_DATE TEXT,
    SHOCK_JSON TEXT,
    DRY_RUN INTEGER,
    RULE_VERSIONS_JSON TEXT,
    PRIMARY KEY (RUN_ID)
);

CREATE TABLE FF_AG_SIGNAL (
    RUN_ID TEXT NOT NULL,
    FORM_ID TEXT NOT NULL,
    BAND TEXT NOT NULL,
    HEADROOM_PCT REAL,
    HEADROOM_TREND REAL,
    MONTHS_TO_BREACH REAL,
    REALISATION_INR NUMERIC,
    UNIT_COST_INR NUMERIC,
    SECONDARY_SIGNALS_JSON TEXT,
    CONFIDENCE REAL,
    DATA_TAGS_JSON TEXT,
    CREATED_AT TEXT NOT NULL,
    PRIMARY KEY (RUN_ID, FORM_ID)
);

CREATE TABLE FF_AG_DEPENDENCY (
    RUN_ID TEXT NOT NULL,
    FORM_ID TEXT NOT NULL,
    N_PRODUCERS_MIN INTEGER NOT NULL,
    HHI REAL NOT NULL,
    TOP_ORIGIN_COUNTRY TEXT,
    TOP_ORIGIN_SHARE REAL,
    CONCENTRATION REAL,
    AFFECTED_MATERIALS_JSON TEXT,
    AFFECTED_WARDS_JSON TEXT,
    CONFIDENCE REAL,
    DATA_TAGS_JSON TEXT,
    CREATED_AT TEXT NOT NULL,
    PRIMARY KEY (RUN_ID, FORM_ID)
);

CREATE TABLE FF_AG_FORECAST (
    RUN_ID TEXT NOT NULL,
    FORM_ID TEXT NOT NULL,
    EXIT_RISK_BAND TEXT NOT NULL,
    EXIT_RISK REAL,
    EXPOSURE REAL,
    WINDOW_MONTHS_LO REAL,
    WINDOW_MONTHS_HI REAL,
    DAYS_OF_COVER REAL,
    STOCKOUT_DATE_IF_EXIT TEXT,
    CAUSE_CODE TEXT NOT NULL,
    CAUSE_FACTS_JSON TEXT,
    CONFIDENCE REAL,
    CREATED_AT TEXT NOT NULL,
    PRIMARY KEY (RUN_ID, FORM_ID)
);

CREATE TABLE FF_AG_SCENARIO (
    RUN_ID TEXT NOT NULL,
    SCENARIO_ID TEXT NOT NULL,
    FORM_ID TEXT NOT NULL,
    OPTION_TYPE TEXT NOT NULL,
    SUPPLIER TEXT,
    MATERIAL TEXT,
    QTY NUMERIC NOT NULL,
    UNIT_RATE_INR NUMERIC,
    COST_INR NUMERIC NOT NULL,
    COVERAGE_DAYS REAL NOT NULL,
    EXPIRY_WASTE_RISK REAL,
    CORRELATED_RISK_FLAG INTEGER,
    CORRELATED_RISK_REASON TEXT,
    RANK_NO INTEGER,
    CREATED_AT TEXT NOT NULL,
    PRIMARY KEY (RUN_ID, SCENARIO_ID)
);

CREATE TABLE FF_AG_RECOMMENDATION (
    RUN_ID TEXT NOT NULL,
    SCENARIO_ID TEXT NOT NULL,
    FORM_ID TEXT NOT NULL,
    OVERALL TEXT NOT NULL,
    NEEDS_SECOND_APPROVER INTEGER,
    DRAFT_PR_JSON TEXT,
    CREATED_AT TEXT NOT NULL,
    PRIMARY KEY (RUN_ID, SCENARIO_ID)
);

CREATE TABLE FF_AG_CHECK (
    RUN_ID TEXT NOT NULL,
    SCENARIO_ID TEXT NOT NULL,
    CHECK_ID TEXT NOT NULL,
    NAME TEXT NOT NULL,
    STATUS TEXT NOT NULL,
    EVIDENCE_JSON TEXT,
    RULE_SOURCE TEXT,
    CREATED_AT TEXT NOT NULL,
    PRIMARY KEY (RUN_ID, SCENARIO_ID, CHECK_ID)
);

CREATE TABLE FF_AG_APPROVAL (
    RUN_ID TEXT NOT NULL,
    SCENARIO_ID TEXT NOT NULL,
    LEVEL_NO INTEGER NOT NULL,
    DECIDED_AT TEXT NOT NULL,
    APPROVER TEXT NOT NULL,
    ACTION TEXT NOT NULL,
    CHECKLIST_JSON TEXT NOT NULL,
    REASON TEXT,
    EDITED_QTY NUMERIC,
    EDITED_SUPPLIER TEXT,
    SNOOZE_DAYS INTEGER,
    PRIMARY KEY (RUN_ID, SCENARIO_ID, LEVEL_NO, DECIDED_AT)
);

CREATE TABLE FF_AG_ACTION (
    RUN_ID TEXT NOT NULL,
    SCENARIO_ID TEXT NOT NULL,
    BANFN TEXT NOT NULL,
    POSTED_AT TEXT NOT NULL,
    POSTED_BY TEXT,
    S4_SERVICE TEXT,
    PAYLOAD_JSON TEXT NOT NULL,
    PAYLOAD_HASH TEXT NOT NULL,
    MASTERDATA_JSON TEXT,
    PRIMARY KEY (RUN_ID, SCENARIO_ID)
);

CREATE TABLE FF_AG_AUDIT_LOG (
    RUN_ID TEXT NOT NULL,
    SEQ INTEGER NOT NULL,
    AGENT TEXT NOT NULL,
    TS TEXT NOT NULL,
    INPUT_HASH TEXT NOT NULL,
    OUTPUT_HASH TEXT NOT NULL,
    RULE_VERSIONS_JSON TEXT,
    DATA_SOURCES_JSON TEXT,
    PREV_HASH TEXT,
    ROW_HASH TEXT NOT NULL,
    PRIMARY KEY (RUN_ID, SEQ)
);
