-- FlowForge schema (plan §6). SAP HANA Cloud dialect; the single source of truth.
-- db/schema_sqlite.sql is GENERATED from this file:  python -m ingest.load_hana --gen-sqlite
--
-- Layout rules (the generator and loader parse this file):
--   * one column per line; table constraints on their own line (PRIMARY KEY (...));
--   * every object is FF_-prefixed and unqualified, so it lands in our own schema;
--   * every REF/MM table ends with the provenance block:
--       SOURCE, SOURCE_URL, FETCHED_AT, IS_PROXY ('REAL' | 'PROXY' | 'SYNTH', agents.contracts.DataTag).
-- Money: INR DECIMAL(15,4). Quantities: DECIMAL(15,3). NPPA ceiling prices exclude GST.

-- ---------------------------------------------------------------------------
-- Config
-- ---------------------------------------------------------------------------
-- AS_OF_DATE pins "today" for the views (demo determinism, backtests). Absent => CURRENT_DATE.
CREATE COLUMN TABLE FF_CFG_PARAM (
    NAME NVARCHAR(60) NOT NULL,
    DATE_VALUE DATE,
    TEXT_VALUE NVARCHAR(500),
    PRIMARY KEY (NAME)
);

-- ---------------------------------------------------------------------------
-- Reference (external)
-- ---------------------------------------------------------------------------
CREATE COLUMN TABLE FF_REF_FORMULATION (
    FORM_ID NVARCHAR(40) NOT NULL,
    GENERIC NVARCHAR(200) NOT NULL,
    DOSAGE_FORM NVARCHAR(60),
    STRENGTH NVARCHAR(60),
    UNIT NVARCHAR(20),
    NLEM_LEVEL NVARCHAR(10),
    THERAPEUTIC_CLASS NVARCHAR(120),
    SOURCE NVARCHAR(120) NOT NULL,
    SOURCE_URL NVARCHAR(500),
    FETCHED_AT TIMESTAMP,
    IS_PROXY NVARCHAR(10) NOT NULL,
    PRIMARY KEY (FORM_ID)
);

-- PARA: DPCO paragraph the price was fixed under (4 | 16 | 19). GST_RATE as a fraction (0.12).
CREATE COLUMN TABLE FF_REF_CEILING_PRICE (
    FORM_ID NVARCHAR(40) NOT NULL,
    EFFECTIVE_FROM DATE NOT NULL,
    SO_NUMBER NVARCHAR(60) NOT NULL,
    CEILING_PRICE DECIMAL(15,4) NOT NULL,
    PARA NVARCHAR(4),
    GST_RATE DECIMAL(6,4),
    SOURCE NVARCHAR(120) NOT NULL,
    SOURCE_URL NVARCHAR(500),
    FETCHED_AT TIMESTAMP,
    IS_PROXY NVARCHAR(10) NOT NULL,
    PRIMARY KEY (FORM_ID, EFFECTIVE_FROM, SO_NUMBER)
);

CREATE COLUMN TABLE FF_REF_API (
    API_ID NVARCHAR(40) NOT NULL,
    NAME NVARCHAR(200) NOT NULL,
    HS8 NVARCHAR(8),
    KSM_ID NVARCHAR(40),
    SOURCE NVARCHAR(120) NOT NULL,
    SOURCE_URL NVARCHAR(500),
    FETCHED_AT TIMESTAMP,
    IS_PROXY NVARCHAR(10) NOT NULL,
    PRIMARY KEY (API_ID)
);

CREATE COLUMN TABLE FF_REF_FORM_API (
    FORM_ID NVARCHAR(40) NOT NULL,
    API_ID NVARCHAR(40) NOT NULL,
    API_MG_PER_UNIT DECIMAL(15,4),
    SOURCE NVARCHAR(120) NOT NULL,
    SOURCE_URL NVARCHAR(500),
    FETCHED_AT TIMESTAMP,
    IS_PROXY NVARCHAR(10) NOT NULL,
    PRIMARY KEY (FORM_ID, API_ID)
);

-- Per-unit cost assumptions for A1: API grams per unit, process yield, conversion/packaging/freight.
CREATE COLUMN TABLE FF_REF_BOM_ASSUMPTION (
    FORM_ID NVARCHAR(40) NOT NULL,
    API_G_PER_UNIT DECIMAL(15,6),
    YIELD DECIMAL(7,6),
    CONVERSION_COST_INR DECIMAL(15,4),
    PACKAGING_COST_INR DECIMAL(15,4),
    FREIGHT_COST_INR DECIMAL(15,4),
    SOURCE NVARCHAR(120) NOT NULL,
    SOURCE_URL NVARCHAR(500),
    FETCHED_AT TIMESTAMP,
    IS_PROXY NVARCHAR(10) NOT NULL,
    PRIMARY KEY (FORM_ID)
);

-- MONTH is the first day of the month.
CREATE COLUMN TABLE FF_REF_API_COST_MONTHLY (
    API_ID NVARCHAR(40) NOT NULL,
    MONTH DATE NOT NULL,
    UNIT_VALUE_INR_KG DECIMAL(15,4),
    QTY_KG DECIMAL(18,3),
    SOURCE NVARCHAR(120) NOT NULL,
    SOURCE_URL NVARCHAR(500),
    FETCHED_AT TIMESTAMP,
    IS_PROXY NVARCHAR(10) NOT NULL,
    PRIMARY KEY (API_ID, MONTH)
);

-- SHARE: fraction of import quantity (0..1).
CREATE COLUMN TABLE FF_REF_API_ORIGIN (
    API_ID NVARCHAR(40) NOT NULL,
    MONTH DATE NOT NULL,
    COUNTRY NVARCHAR(60) NOT NULL,
    SHARE DECIMAL(7,6),
    SOURCE NVARCHAR(120) NOT NULL,
    SOURCE_URL NVARCHAR(500),
    FETCHED_AT TIMESTAMP,
    IS_PROXY NVARCHAR(10) NOT NULL,
    PRIMARY KEY (API_ID, MONTH, COUNTRY)
);

CREATE COLUMN TABLE FF_REF_MANUFACTURER (
    ID NVARCHAR(40) NOT NULL,
    NAME NVARCHAR(200) NOT NULL,
    STATE NVARCHAR(60),
    LICENCE_NO NVARCHAR(80),
    SOURCE NVARCHAR(120) NOT NULL,
    SOURCE_URL NVARCHAR(500),
    FETCHED_AT TIMESTAMP,
    IS_PROXY NVARCHAR(10) NOT NULL,
    PRIMARY KEY (ID)
);

-- Evidence that a manufacturer makes a formulation. Counts are LOWER BOUNDS ("at least N").
CREATE COLUMN TABLE FF_REF_PRODUCER (
    FORM_ID NVARCHAR(40) NOT NULL,
    MANUFACTURER_ID NVARCHAR(40) NOT NULL,
    EVIDENCE_SOURCE NVARCHAR(200),
    MARKET_SHARE DECIMAL(7,6),
    SOURCE NVARCHAR(120) NOT NULL,
    SOURCE_URL NVARCHAR(500),
    FETCHED_AT TIMESTAMP,
    IS_PROXY NVARCHAR(10) NOT NULL,
    PRIMARY KEY (FORM_ID, MANUFACTURER_ID)
);

CREATE COLUMN TABLE FF_REF_WPI (
    MONTH DATE NOT NULL,
    SERIES NVARCHAR(120) NOT NULL,
    INDEX_VALUE DECIMAL(12,4),
    SOURCE NVARCHAR(120) NOT NULL,
    SOURCE_URL NVARCHAR(500),
    FETCHED_AT TIMESTAMP,
    IS_PROXY NVARCHAR(10) NOT NULL,
    PRIMARY KEY (MONTH, SERIES)
);

-- CDSCO "not of standard quality" alerts. FORM_ID is filled when the drug could be matched.
CREATE COLUMN TABLE FF_REF_NSQ_ALERT (
    ALERT_ID NVARCHAR(40) NOT NULL,
    MONTH DATE NOT NULL,
    DRUG NVARCHAR(300) NOT NULL,
    BATCH NVARCHAR(60) NOT NULL,
    MANUFACTURER_ID NVARCHAR(40),
    FORM_ID NVARCHAR(40),
    REASON NVARCHAR(500),
    SOURCE NVARCHAR(120) NOT NULL,
    SOURCE_URL NVARCHAR(500),
    FETCHED_AT TIMESTAMP,
    IS_PROXY NVARCHAR(10) NOT NULL,
    PRIMARY KEY (ALERT_ID)
);

-- ---------------------------------------------------------------------------
-- Hospital MM (S/4-shaped, synthetic). Field names follow the S/4 tables.
-- ---------------------------------------------------------------------------
-- VED/ABC/FSN classes; RAUBE storage condition; XCHPF 'X' = batch-managed.
CREATE COLUMN TABLE FF_MM_MARA (
    MATNR NVARCHAR(40) NOT NULL,
    MAKTX NVARCHAR(200),
    GENERIC NVARCHAR(200),
    STRENGTH NVARCHAR(60),
    MEINS NVARCHAR(3),
    VED NVARCHAR(1),
    ABC NVARCHAR(1),
    FSN NVARCHAR(1),
    RAUBE NVARCHAR(20),
    XCHPF NVARCHAR(1),
    FORM_ID NVARCHAR(40),
    SOURCE NVARCHAR(120) NOT NULL,
    SOURCE_URL NVARCHAR(500),
    FETCHED_AT TIMESTAMP,
    IS_PROXY NVARCHAR(10) NOT NULL,
    PRIMARY KEY (MATNR)
);

-- SPERR 'X' = blocked / blacklisted supplier.
CREATE COLUMN TABLE FF_MM_LFA1 (
    LIFNR NVARCHAR(20) NOT NULL,
    NAME1 NVARCHAR(200) NOT NULL,
    GSTIN NVARCHAR(15),
    DRUG_LICENCE_NO NVARCHAR(80),
    SPERR NVARCHAR(1),
    SOURCE NVARCHAR(120) NOT NULL,
    SOURCE_URL NVARCHAR(500),
    FETCHED_AT TIMESTAMP,
    IS_PROXY NVARCHAR(10) NOT NULL,
    PRIMARY KEY (LIFNR)
);

CREATE COLUMN TABLE FF_MM_T001W (
    WERKS NVARCHAR(4) NOT NULL,
    NAME1 NVARCHAR(120) NOT NULL,
    ORT01 NVARCHAR(60),
    REGIO NVARCHAR(10),
    LOC_TYPE NVARCHAR(30),
    SOURCE NVARCHAR(120) NOT NULL,
    SOURCE_URL NVARCHAR(500),
    FETCHED_AT TIMESTAMP,
    IS_PROXY NVARCHAR(10) NOT NULL,
    PRIMARY KEY (WERKS)
);

-- Batch stock. CLABS unrestricted, CINSM quality inspection (quarantine), CSPEM blocked.
CREATE COLUMN TABLE FF_MM_MCHB (
    MATNR NVARCHAR(40) NOT NULL,
    WERKS NVARCHAR(4) NOT NULL,
    LGORT NVARCHAR(4) NOT NULL,
    CHARG NVARCHAR(20) NOT NULL,
    CLABS DECIMAL(15,3) NOT NULL,
    CINSM DECIMAL(15,3),
    CSPEM DECIMAL(15,3),
    VFDAT DATE NOT NULL,
    HSDAT DATE,
    MANUFACTURER_ID NVARCHAR(40),
    SOURCE NVARCHAR(120) NOT NULL,
    SOURCE_URL NVARCHAR(500),
    FETCHED_AT TIMESTAMP,
    IS_PROXY NVARCHAR(10) NOT NULL,
    PRIMARY KEY (MATNR, WERKS, LGORT, CHARG)
);

-- Movements: 101 GR, 261/201 GI to ward (262/202 reversals), 311 transfer, 122 return, 551 scrap.
-- MENGE is always positive; BWART gives the direction. KOSTL = consuming ward.
CREATE COLUMN TABLE FF_MM_MSEG (
    MBLNR NVARCHAR(10) NOT NULL,
    MJAHR INTEGER NOT NULL,
    ZEILE INTEGER NOT NULL,
    BWART NVARCHAR(3) NOT NULL,
    MATNR NVARCHAR(40) NOT NULL,
    WERKS NVARCHAR(4) NOT NULL,
    LGORT NVARCHAR(4),
    CHARG NVARCHAR(20),
    MENGE DECIMAL(15,3) NOT NULL,
    MEINS NVARCHAR(3),
    BUDAT DATE NOT NULL,
    UMWRK NVARCHAR(4),
    KOSTL NVARCHAR(10),
    LIFNR NVARCHAR(20),
    EBELN NVARCHAR(10),
    EBELP INTEGER,
    SOURCE NVARCHAR(120) NOT NULL,
    SOURCE_URL NVARCHAR(500),
    FETCHED_AT TIMESTAMP,
    IS_PROXY NVARCHAR(10) NOT NULL,
    PRIMARY KEY (MBLNR, MJAHR, ZEILE)
);

CREATE COLUMN TABLE FF_MM_EKKO (
    EBELN NVARCHAR(10) NOT NULL,
    BSART NVARCHAR(4),
    LIFNR NVARCHAR(20) NOT NULL,
    BEDAT DATE NOT NULL,
    WAERS NVARCHAR(5),
    SOURCE NVARCHAR(120) NOT NULL,
    SOURCE_URL NVARCHAR(500),
    FETCHED_AT TIMESTAMP,
    IS_PROXY NVARCHAR(10) NOT NULL,
    PRIMARY KEY (EBELN)
);

-- EINDT = promised delivery date. Actual delivery = first 101 GR in FF_MM_MSEG (see FF_V_SUPPLIER_OTD).
CREATE COLUMN TABLE FF_MM_EKPO (
    EBELN NVARCHAR(10) NOT NULL,
    EBELP INTEGER NOT NULL,
    MATNR NVARCHAR(40) NOT NULL,
    WERKS NVARCHAR(4) NOT NULL,
    MENGE DECIMAL(15,3) NOT NULL,
    MEINS NVARCHAR(3),
    NETPR DECIMAL(15,4),
    PEINH INTEGER,
    EINDT DATE NOT NULL,
    SOURCE NVARCHAR(120) NOT NULL,
    SOURCE_URL NVARCHAR(500),
    FETCHED_AT TIMESTAMP,
    IS_PROXY NVARCHAR(10) NOT NULL,
    PRIMARY KEY (EBELN, EBELP)
);

-- Purchase requisitions. A6 writes here only for a (RUN_ID, SCENARIO_ID) with an approving FF_AG_APPROVAL row.
CREATE COLUMN TABLE FF_MM_EBAN (
    BANFN NVARCHAR(10) NOT NULL,
    BNFPO INTEGER NOT NULL,
    MATNR NVARCHAR(40) NOT NULL,
    WERKS NVARCHAR(4) NOT NULL,
    MENGE DECIMAL(15,3) NOT NULL,
    MEINS NVARCHAR(3),
    PREIS DECIMAL(15,4),
    PEINH INTEGER,
    BADAT DATE NOT NULL,
    LFDAT DATE,
    FLIEF NVARCHAR(20),
    AFNAM NVARCHAR(40),
    STATUS NVARCHAR(20),
    RUN_ID NVARCHAR(40),
    SCENARIO_ID NVARCHAR(40),
    SOURCE NVARCHAR(120) NOT NULL,
    SOURCE_URL NVARCHAR(500),
    FETCHED_AT TIMESTAMP,
    IS_PROXY NVARCHAR(10) NOT NULL,
    PRIMARY KEY (BANFN, BNFPO)
);

-- EXCURSION_FLAG: 1 = outside the storage range.
CREATE COLUMN TABLE FF_MM_COLDCHAIN (
    LOCATION NVARCHAR(20) NOT NULL,
    TS TIMESTAMP NOT NULL,
    TEMP_C DECIMAL(5,2),
    EXCURSION_FLAG TINYINT,
    SOURCE NVARCHAR(120) NOT NULL,
    SOURCE_URL NVARCHAR(500),
    FETCHED_AT TIMESTAMP,
    IS_PROXY NVARCHAR(10) NOT NULL,
    PRIMARY KEY (LOCATION, TS)
);

-- ---------------------------------------------------------------------------
-- Graph (vertex/edge tables). The workspace itself is created in db/graph.sql (S05).
-- ---------------------------------------------------------------------------
CREATE COLUMN TABLE FF_G_V (
    ID NVARCHAR(80) NOT NULL,
    TYPE NVARCHAR(30) NOT NULL,
    LABEL NVARCHAR(200),
    PRIMARY KEY (ID)
);

CREATE COLUMN TABLE FF_G_E (
    ID NVARCHAR(160) NOT NULL,
    SRC NVARCHAR(80) NOT NULL,
    DST NVARCHAR(80) NOT NULL,
    REL NVARCHAR(40) NOT NULL,
    PRIMARY KEY (ID)
);

-- ---------------------------------------------------------------------------
-- Agent layer. Columns mirror agents/contracts.py (the single source of truth);
-- nested parts (lists, dicts, checklists) are stored as JSON text in *_JSON columns.
-- ---------------------------------------------------------------------------
-- RunContext. STATUS: RUNNING | DONE | FAILED.
CREATE COLUMN TABLE FF_AG_RUN (
    RUN_ID NVARCHAR(40) NOT NULL,
    STARTED_AT TIMESTAMP NOT NULL,
    FINISHED_AT TIMESTAMP,
    TRIGGER_TYPE NVARCHAR(20) NOT NULL,
    STATUS NVARCHAR(20) NOT NULL,
    FORMULATION_IDS_JSON NVARCHAR(2000),
    AS_OF_DATE DATE,
    SHOCK_JSON NVARCHAR(1000),
    DRY_RUN TINYINT,
    RULE_VERSIONS_JSON NVARCHAR(1000),
    PRIMARY KEY (RUN_ID)
);

-- A1 RiskSignal.
CREATE COLUMN TABLE FF_AG_SIGNAL (
    RUN_ID NVARCHAR(40) NOT NULL,
    FORM_ID NVARCHAR(40) NOT NULL,
    BAND NVARCHAR(10) NOT NULL,
    HEADROOM_PCT DOUBLE,
    HEADROOM_TREND DOUBLE,
    MONTHS_TO_BREACH DOUBLE,
    REALISATION_INR DECIMAL(15,4),
    UNIT_COST_INR DECIMAL(15,4),
    SECONDARY_SIGNALS_JSON NVARCHAR(2000),
    CONFIDENCE DOUBLE,
    DATA_TAGS_JSON NVARCHAR(2000),
    CREATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (RUN_ID, FORM_ID)
);

-- A2 DependencyProfile. N_PRODUCERS_MIN is a lower bound ("at least N producers").
CREATE COLUMN TABLE FF_AG_DEPENDENCY (
    RUN_ID NVARCHAR(40) NOT NULL,
    FORM_ID NVARCHAR(40) NOT NULL,
    N_PRODUCERS_MIN INTEGER NOT NULL,
    HHI DOUBLE NOT NULL,
    TOP_ORIGIN_COUNTRY NVARCHAR(60),
    TOP_ORIGIN_SHARE DOUBLE,
    CONCENTRATION DOUBLE,
    AFFECTED_MATERIALS_JSON NVARCHAR(2000),
    AFFECTED_WARDS_JSON NVARCHAR(2000),
    CONFIDENCE DOUBLE,
    DATA_TAGS_JSON NVARCHAR(2000),
    CREATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (RUN_ID, FORM_ID)
);

-- A3 Forecast. A probabilistic flag for review, never a statement of intent.
CREATE COLUMN TABLE FF_AG_FORECAST (
    RUN_ID NVARCHAR(40) NOT NULL,
    FORM_ID NVARCHAR(40) NOT NULL,
    EXIT_RISK_BAND NVARCHAR(10) NOT NULL,
    EXIT_RISK DOUBLE,
    EXPOSURE DOUBLE,
    WINDOW_MONTHS_LO DOUBLE,
    WINDOW_MONTHS_HI DOUBLE,
    DAYS_OF_COVER DOUBLE,
    STOCKOUT_DATE_IF_EXIT DATE,
    CAUSE_CODE NVARCHAR(30) NOT NULL,
    CAUSE_FACTS_JSON NVARCHAR(4000),
    CONFIDENCE DOUBLE,
    CREATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (RUN_ID, FORM_ID)
);

-- A4 Scenario.
CREATE COLUMN TABLE FF_AG_SCENARIO (
    RUN_ID NVARCHAR(40) NOT NULL,
    SCENARIO_ID NVARCHAR(40) NOT NULL,
    FORM_ID NVARCHAR(40) NOT NULL,
    OPTION_TYPE NVARCHAR(20) NOT NULL,
    SUPPLIER NVARCHAR(40),
    MATERIAL NVARCHAR(40),
    QTY DECIMAL(15,3) NOT NULL,
    UNIT_RATE_INR DECIMAL(15,4),
    COST_INR DECIMAL(15,4) NOT NULL,
    COVERAGE_DAYS DOUBLE NOT NULL,
    EXPIRY_WASTE_RISK DOUBLE,
    CORRELATED_RISK_FLAG TINYINT,
    RANK_NO INTEGER,
    CREATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (RUN_ID, SCENARIO_ID)
);

-- A5 Recommendation. OVERALL: READY | NEEDS_CHANGES | BLOCKED. DRAFT_PR_JSON is the S/4 payload.
CREATE COLUMN TABLE FF_AG_RECOMMENDATION (
    RUN_ID NVARCHAR(40) NOT NULL,
    SCENARIO_ID NVARCHAR(40) NOT NULL,
    FORM_ID NVARCHAR(40) NOT NULL,
    OVERALL NVARCHAR(20) NOT NULL,
    NEEDS_SECOND_APPROVER TINYINT,
    DRAFT_PR_JSON NVARCHAR(2000),
    CREATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (RUN_ID, SCENARIO_ID)
);

-- A5 CheckResult. STATUS: PASS | WARN | FAIL.
CREATE COLUMN TABLE FF_AG_CHECK (
    RUN_ID NVARCHAR(40) NOT NULL,
    SCENARIO_ID NVARCHAR(40) NOT NULL,
    CHECK_ID NVARCHAR(40) NOT NULL,
    NAME NVARCHAR(200) NOT NULL,
    STATUS NVARCHAR(4) NOT NULL,
    EVIDENCE_JSON NVARCHAR(4000),
    RULE_SOURCE NVARCHAR(200),
    CREATED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (RUN_ID, SCENARIO_ID, CHECK_ID)
);

-- Human gate ApprovalDecision. ACTION: APPROVE | EDIT_APPROVE | REJECT | SNOOZE.
-- A6 acts only when an APPROVE / EDIT_APPROVE row exists for the (RUN_ID, SCENARIO_ID).
CREATE COLUMN TABLE FF_AG_APPROVAL (
    RUN_ID NVARCHAR(40) NOT NULL,
    SCENARIO_ID NVARCHAR(40) NOT NULL,
    LEVEL_NO TINYINT NOT NULL,
    DECIDED_AT TIMESTAMP NOT NULL,
    APPROVER NVARCHAR(120) NOT NULL,
    ACTION NVARCHAR(20) NOT NULL,
    CHECKLIST_JSON NVARCHAR(1000) NOT NULL,
    REASON NVARCHAR(1000),
    EDITED_QTY DECIMAL(15,3),
    EDITED_SUPPLIER NVARCHAR(40),
    SNOOZE_DAYS INTEGER,
    PRIMARY KEY (RUN_ID, SCENARIO_ID, LEVEL_NO, DECIDED_AT)
);

-- A6 AuditEvent. Append-only, hash-chained: never UPDATE or DELETE.
-- PREV_HASH is NULL only for the first event of a chain; ROW_HASH is the event hash.
CREATE COLUMN TABLE FF_AG_AUDIT_LOG (
    RUN_ID NVARCHAR(40) NOT NULL,
    SEQ INTEGER NOT NULL,
    AGENT NVARCHAR(20) NOT NULL,
    TS TIMESTAMP NOT NULL,
    INPUT_HASH NVARCHAR(64) NOT NULL,
    OUTPUT_HASH NVARCHAR(64) NOT NULL,
    RULE_VERSIONS_JSON NVARCHAR(1000),
    DATA_SOURCES_JSON NVARCHAR(4000),
    PREV_HASH NVARCHAR(64),
    ROW_HASH NVARCHAR(64) NOT NULL,
    PRIMARY KEY (RUN_ID, SEQ)
);
